ssad/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index,name='Index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('login_nocaptha/', views.Login_nocaptha, name="login_nocaptha"),
    path('home/',views.index,name='home'),
    path('logout/',views.logout_view,name='logout'),
    path('attaque_dictionnaire/', views.attaque_dictionnaire_requests, name='attaque_dictionnaire'),
    path('attaque_dictionnaire_un_zero_3char_requests/', views.attaque_dictionnaire_un_zero_3char_requests, name='attaque_dictionnaire_un_zero_3char_requests'),
    path('attaque_brute_force_number_requests/', views.attaque_brute_force_number_requests, name='attaque_brute_force_number_requests'),
    path('attaque_brute_force_un_zero_3char_requests/', views.attaque_brute_force_un_zero_3char_requests, name='attaque_brute_force_un_zero_3char_requests'),
    path('attaque_brute_force_all_char_requests/', views.attaque_brute_force_all_char_requests, name='attaque_brute_force_all_char_requests'),
    path('Steganography_encode/', views.Steganography_encode, name='Steganography_encode'),
    path('Steganography_decode/', views.Steganography_decode, name='Steganography_decode'),

    path('user_messages/', views.user_messages, name='user_messags'),
    path('decryption/', views.menu, name='menu'),
    path('decrypt_message/', views.decrypt_message, name='decrypt_message'),
    path('decrypt_affine/', views.decrypt_affine, name='decrypt_affine'),
    path('decrypt_cesar/', views.decrypt_cesar, name='decrypt_cesar'),
    path('decrypt_mirroir/', views.decrypt_mirroir, name='decrypt_mirroir'),
    path('sidebar/', views.sidebar, name='sidebar'),
    path('compose/', views.compose_message, name='compose_message'),
    path('custom_logout/', views.custom_logout, name='custom_logout'),

]

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm, User
from .models import *




class CustomLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')



class MessageForm(forms.ModelForm):
    ENCRYPTION_CHOICES = (
            ('', 'Select an encryption method '),
            ('cesar', 'Ceasar'),
            ('mirror', 'Mirror'),
            ('affine', 'Affine'),
            ('shift', 'Shift Right/Left'),
    )

    encryption_method = forms.ChoiceField(
        label="Encryption method :",
        choices=ENCRYPTION_CHOICES,
    )
    encryption_key = forms.IntegerField(label="Key a ",required=False)
    encryptionb_key= forms.IntegerField(label="Key b ",required=False)
    encryption_direction = forms.ChoiceField(
        choices=[('left', 'Left'), ('right', 'Right')],
        required=False
    )
    content=forms.CharField(widget=forms.Textarea(attrs={'class': 'custom-class-5'}))  # Exemple pour le champ 'content'

    class Meta:
        model = Message
        fields = ['receiver', 'encryption_method', 'encryption_key','encryptionb_key' ,'encryption_direction','content']

app/templates/Steganographydecode.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>CryptoWarEnigma</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="{% static 'img/cryptography.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
        <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <!-- Vendor CSS Files -->

    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css1/sheet1.css' %}" rel="stylesheet">

    <style>
        /* Style de base pour le conteneur principal */
        /* Style de base pour le conteneur principal */
        #header {
      position: fixed;
      top: 0;
      left: 0;
      bottom: 0;
      width: 260px;
      transition: all ease-in-out 0.5s;
      z-index: 9997;
      transition: all 0.5s;
      padding: 0 15px;
      background: #000205;
      overflow-y: auto;
      overflow-x: hidden;


    }

    #header::-webkit-scrollbar {
        width: 0;
        /* Largeur de la scrollbar à zéro */
    }

    #header::-webkit-scrollbar-track {
        background-color: transparent;
        /* Couleur de la piste de la scrollbar */
    }

    #header::-webkit-scrollbar-thumb {
        background-color: transparent;
        /* Couleur de la poignée de la scrollbar */
        border: none;
        /* Supprime la bordure de la poignée */
        margin-right: -16px;
        /* Crée un espace réservé pour la barre de défilement invisible */
    }

        #hero:before {
            content: "";
            background: rgba(5, 13, 24, 0.3);
            position: absolute;
            bottom: 0;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1;
        }

        #hero .hero-container {
            position: relative;
            z-index: 2;
            min-width: 300px;
            margin-left: 200px;
            overflow-y: auto;
            overflow-x: hidden;


        }

        #hero .hero-container::-webkit-scrollbar {
            width: 0;
            /* Largeur de la scrollbar à zéro */
        }

        #hero .hero-container::-webkit-scrollbar-track {
            background-color: transparent;
            /* Couleur de la piste de la scrollbar */
        }

        #hero .hero-container::-webkit-scrollbar-thumb {
            background-color: transparent;
            /* Couleur de la poignée de la scrollbar */
            border: none;
            /* Supprime la bordure de la poignée */
            margin-right: -16px;
            /* Crée un espace réservé pour la barre de défilement invisible */
        }



        #hero p {
            color: #fff;
            margin-bottom: 2px;
            font-size: 22px;
            font-family: "Poppins", sans-serif;
        }

        #hero p span {
            color: #fff;
            padding-bottom: 4px;
            letter-spacing: 1px;
            border-bottom: 3px solid;
            background: black;
        }


        /* Style pour le titre principal (h1) */
        .hero-container h1 {
            font-size: 20px;
            color: #fff;
            /* Couleur de texte de votre choix */
            margin-bottom: 20px;
        }

        /* Style pour le formulaire */


        /* Style pour le champ "Nom d'utilisateur" */
        .hero-container form {
            width: 900px;
            margin: 20px 0;
            text-align: center;

        }

        /* Style pour l'élément d'entrée de fichier */
        input[type="file"] {
            display: block;
            margin: 0 auto;
            color: #fff;
            background-color: #333;
            padding: 10px;
            border: 1px solid #ccc;
            /* Bordure autour de l'élément de fichier */
            border-radius: 30px;
            width: 100%;
            margin: 10px 0;
        }

        /* Style pour la zone de texte (textarea) */
        textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            /* Couleur de bordure de votre choix */
            border-radius: 30px;
            height: 100px;
            margin: 5px 0;
            color: #fff;
            background-color: #333;
        }

        /* Style pour le bouton "Encode Image" */
        button[type="submit"] {
            background-color: #333;
            /* Couleur de fond de votre choix */
            color: #fff;
            /* Couleur de texte pour le bouton */
            padding: 10px 20px;
            border: none;
            border-radius: 50px;
            cursor: pointer;
            font-weight: bold;
            width: 200px;
            transition: background-color 0.3s;
        }

        /* Style au survol du bouton "commencer" */
        button[type="submit"]:hover {
            background-color: rgb(83, 83, 81);
            /* Nouvelle couleur de fond au survol */
        }


        .message {
            width: 800px;

        }
    </style>


</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="d-flex flex-column">
            <div class="profile">
                <h1 class="rotate">CryptoWarEnigma</h1>
                <h1 class="text-light"><a href="{% url 'home' %}">{{username}}</a></h1>
            </div>

            <nav id="navbar" class="nav-menu navbar">
                <ul>
                  <li><a href="{% url 'home' %}" class="nav-link scrollto active"><i class="bx bx-home"></i>
                      <span>Home</span></a></li>
                  <li><a href="{% url 'user_messags' %}" class="nav-link scrollto"><i class="bx bx-user"></i>
                      <span>Inbox</span></a></li>
                  <li><a href="{% url 'compose_message' %}" class=""><i class="bi bi-chat-left-text-fill"></i> <span>Send
                        Message</span></a></li>
        
                  <li><a href="{% url 'attaque_dictionnaire_un_zero_3char_requests'%}" class=""><span
                        class="material-symbols-outlined">
                        lab_profile
                      </span>
                      <span> Dictionnaire 0 1 </span></a></li>
        
                  <li><a href="{% url 'attaque_dictionnaire'%}" class=""><span class="material-symbols-outlined">
                        export_notes
                      </span>
                      <span> Dictionnaire number</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_un_zero_3char_requests'%}" class=""><span
                        class="material-symbols-outlined">
                        mitre
                      </span> <span> Force brute  0 1</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_number_requests'%}" class=""><span class="material-symbols-outlined">
                        nfc
                      </span>
                      <span> Force brute  number</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_all_char_requests'%}" class=""><i class="bx bx-book-content"></i>
                      <span>Force brute char</span></a></li>
                  <li><a href="{% url 'Steganography_encode'%}" class=""><span class="material-symbols-outlined">
                    rear_camera
                    </span>
                      <span> steganographie</span></a></li>
                  <li><a href="{% url 'Steganography_decode'%}" class=""><i class="bx bx-server"></i> <span> View
                        steganographie</span></a></li>
                </ul>
                <ul>
                  <li><a href="{% url 'logout'%}" class=""><i class="bi bi-box-arrow-left"></i> <span>Log
                        Out</span></a></li>
                </ul>
              </nav><!-- .nav-menu -->
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex flex-column justify-content-center align-items-center">
        <div class="hero-container">
            <h1>Decode image</h1>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="image" accept="image/*" required>
                <button type="submit">decode Image</button>
            </form>
            <div class="message">


                {% if decoded_data %}
                <p>Résultats de decodage de la Steganography:</p>
                <p>Le message trouvé : {{ decoded_data }}</p>
                {% endif %}
            </div>



        </div>
    </section>
    <!-- End Hero -->
    <main id="main">


    </main><!-- End #main -->



    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
    <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

app/templates/attaque_dictionnaire.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>CryptoWarEnigma</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="{% static 'img/cryptography.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

        <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />    

    <!-- Vendor CSS Files -->

    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css1/sheet1.css' %}" rel="stylesheet">

    <style>
        /* Style de base pour le conteneur principal */
        /* Style de base pour le conteneur principal */

        #header {
            position: fixed;
            top: 0;
            left: 0;
            bottom: 0;
            width: 260px;
            transition: all ease-in-out 0.5s;
            z-index: 9997;
            transition: all 0.5s;
            padding: 0 15px;
            background: #000205;
            overflow-y: auto;
            overflow-x: hidden;


        }

        #header::-webkit-scrollbar {
            width: 0;
            /* Largeur de la scrollbar à zéro */
        }

        #header::-webkit-scrollbar-track {
            background-color: transparent;
            /* Couleur de la piste de la scrollbar */
        }

        #header::-webkit-scrollbar-thumb {
            background-color: transparent;
            /* Couleur de la poignée de la scrollbar */
            border: none;
            /* Supprime la bordure de la poignée */
            margin-right: -16px;
            /* Crée un espace réservé pour la barre de défilement invisible */
        }

        #hero:before {
            content: "";
            background: rgba(5, 13, 24, 0.3);
            position: absolute;
            bottom: 0;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1;
        }

        #hero .hero-container {
            position: relative;
            z-index: 2;
            min-width: 300px;
            padding: 20px;
            width: 600px;
            margin-left: 100px;
        }



        #hero p {
            color: #fff;
            margin-bottom: 2px;
            font-size: 22px;
            font-family: "Poppins", sans-serif;
        }

        #hero p span {
            color: #fff;
            padding-bottom: 4px;
            letter-spacing: 1px;
            border-bottom: 3px solid;
            background: black;
        }


        /* Style pour le titre principal (h1) */
        .hero-container h1 {
            font-size: 40px;
            color: #fff;
            /* Couleur de texte de votre choix */
            margin-bottom: 20px;
        }

        /* Style pour le formulaire */
        .hero-container form {
            width: 600px;
            margin: 20px 0;
            text-align: center;

        }

        /* Style pour l'étiquette du champ "Nom d'utilisateur" */
        .hero-container label {
            font-weight: bold;
            color: #fff;
            margin-bottom: 2px;
            font-size: 22px;
            /* Couleur de texte de votre choix */
        }

        /* Style pour le champ "Nom d'utilisateur" */
        .hero-container input[type="text"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            /* Couleur de bordure de votre choix */
            border-radius: 40px;
            margin: 5px 0;
            color: #fff;
            background-color: #333;
        }

        /* Style pour le bouton "commencer" */
        .hero-container input[type="submit"] {
            background-color: #333;
            /* Couleur de fond de votre choix */
            color: #fff;
            /* Couleur de texte pour le bouton */
            padding: 10px 20px;
            border: none;
            border-radius: 50px;
            cursor: pointer;
            font-weight: bold;
            transition: background-color 0.3s;
        }



        /* Style au survol du bouton "commencer" */
        .hero-container input[type="submit"]:hover {
            background-color: rgb(83, 83, 81);
            /* Nouvelle couleur de fond au survol */
        }

        /* Style pour les messages */
        .hero-container_message {
            margin-top: 20px;
        }

        /* Style pour les titres des messages (h2) */
        .hero-container_message h2 {
            font-size: 20px;
            margin-bottom: 10px;
        }

        /* Style pour les paragraphes dans les messages */
        .hero-container_message p {
            font-size: 16px;
        }

        .error-message {
            text-align: center;
            background-color: #ff0000;
            /* Couleur de fond pour le message d'erreur */
            color: #fff;
            /* Couleur de texte pour le message d'erreur */
            padding: 10px;
            margin: 20px auto;
            border-radius: 5px;
            width: 70%;
        }
    </style>


</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="d-flex flex-column">
            <div class="profile">
                <h1 class="rotate">CryptoWarEnigma</h1>
                <h1 class="text-light"><a href="{% url 'home' %}">{{username}}</a></h1>
            </div>

            <nav id="navbar" class="nav-menu navbar">
                <ul>
                  <li><a href="{% url 'home' %}" class="nav-link scrollto active"><i class="bx bx-home"></i>
                      <span>Home</span></a></li>
                  <li><a href="{% url 'user_messags' %}" class="nav-link scrollto"><i class="bx bx-user"></i>
                      <span>Inbox</span></a></li>
                  <li><a href="{% url 'compose_message' %}" class=""><i class="bi bi-chat-left-text-fill"></i> <span>Send
                        Message</span></a></li>
        
                  <li><a href="{% url 'attaque_dictionnaire_un_zero_3char_requests'%}" class=""><span
                        class="material-symbols-outlined">
                        lab_profile
                      </span>
                      <span> Dictionnaire 0 1 </span></a></li>
        
                  <li><a href="{% url 'attaque_dictionnaire'%}" class=""><span class="material-symbols-outlined">
                        export_notes
                      </span>
                      <span> Dictionnaire number</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_un_zero_3char_requests'%}" class=""><span
                        class="material-symbols-outlined">
                        mitre
                      </span> <span> Force brute  0 1</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_number_requests'%}" class=""><span class="material-symbols-outlined">
                        nfc
                      </span>
                      <span> Force brute  number</span></a></li>
        
                  <li><a href="{% url 'attaque_brute_force_all_char_requests'%}" class=""><i class="bx bx-book-content"></i>
                      <span>Force brute char</span></a></li>
                  <li><a href="{% url 'Steganography_encode'%}" class=""><span class="material-symbols-outlined">
                    rear_camera
                    </span>
                      <span> steganographie</span></a></li>
                  <li><a href="{% url 'Steganography_decode'%}" class=""><i class="bx bx-server"></i> <span> View
                        steganographie</span></a></li>
                </ul>
                <ul>
                  <li><a href="{% url 'logout'%}" class=""><i class="bi bi-box-arrow-left"></i> <span>Log
                        Out</span></a></li>
                </ul>
              </nav><!-- .nav-menu -->
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex flex-column justify-content-center align-items-center">
        <div class="hero-container">
            <h1>Attaque par dictionnaire</h1>
            <p>Chiffres de 0 à 9 de 5 caractères</p>

            <form method="post">
                {% csrf_token %}
                <label for="username">Nom d'utilisateur:</label>
                <input type="text" id="username" name="username" required><br><br>

                <input type="submit" value="commencer">
            </form>
            <div class="hero-container_message">
                {% if success %}
                <p>Résultats de la tentative de connexion :</p>
                <p>Mot de passe trouvé : {{ password }}</p>
                <p>Temps d'exécution : {{ temp_execution }} secondes</p>
                {% endif %}

                {% if nosuccess %}
                <div class="error-message">
                    <p>Aucun mot de passe valide trouvé pour cet utilisateur.</p>
                    <p>Temps d'exécution : {{ temp_execution }} secondes</p>
                </div>
                {% endif %}
            </div>

        </div>
    </section>
    <!-- End Hero -->
    <main id="main">


    </main><!-- End #main -->



    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="{% static 'vendor/typed.js/typed.umd.js' %}"></script>
    <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

app/templates/compose.html
{% extends 'base.html' %} 
{% block extrahead %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
    body {
        background-color: #000205; /* Dark background color */
        color: #fff; /* Light text color */
        font-family: poppins, sans-serif;
    }
    
    h2 {
        text-align: center;
        margin-top:5px;
        margin-bottom:15px;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #201f1f; /* Dark form background color */
        border: 1px solid #444; /* Dark border color */
        border-radius: 15px; /* Increased border radius for depth */
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.4); /* Increased box shadow for depth */
    }

    label {
        display: block;
        margin-bottom: 10px;
    }


    input[type="text"], select {
        background-color: #555;
        border: none;
        color: #fff;
        padding: 10px;
        border-radius: 10px;
        font-family: 'poppins', sans-serif;
        margin-bottom: 10px;
        width: 80%;
    }
    input[type="number"]{
        background-color: #555;
        border: none;
        color: #fff;
        padding: 10px;
        border-radius: 10px;
        font-family: 'poppins', sans-serif;
        margin-bottom: 10px;
        width:50%;
    }




    textarea {
        background-color: #fff;
        font-family: 'poppins', sans-serif;
        border-radius: 5px;
        margin-bottom:0;
        padding:10px;
    }

    button {
        color: black;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-family: 'poppins', sans-serif;
        margin-top: 0;
        background: #fff;
        outline: none;
        cursor: pointer;
        font-size: 1em;
        font-weight: 600;
        position:relative;
        left: 287px;
    }
    
    button:hover {
        background-color: #555;
    }
    a {
        color: #007BFF; /* Blue link color */
        text-decoration: none;
    }

    .error-message {
        background-color: #ff0000; /* Rouge pour la boîte d'erreur */
        color: #fff; /* Texte blanc */
        border-radius: 10px; /* Rayon de bordure arrondi */
        padding: 10px; /* Espacement intérieur */
        position:relative;
        margin-top:10px;
        left:260px;
        width:78%;
        margin-left:0;
        text-align: center; /* Centrer le texte dans la boîte */
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            // Initially, hide both encryption key and encryption direction fields
            $('#id_encryption_key').parent().hide();
            $('#id_encryptionb_key').parent().hide();
            $('#id_encryption_direction').parent().hide();

            // Add change event listener to the encryption method select field
            $('#id_encryption_method').on('change', function () {
                var selectedMethod = $(this).val();
                if (selectedMethod === 'cesar') {
                    $('#id_encryption_key').parent().show();
                    $('#id_encryptionb_key').parent().hide();
                    $('#id_encryption_direction').parent().show();
                } else if (selectedMethod === 'mirror') {
                    $('#id_encryption_key').parent().hide();
                    $('#id_encryptionb_key').parent().hide();
                    $('#id_encryption_direction').parent().hide();
                } else if(selectedMethod === 'shift') {
                    $('#id_encryption_key').parent().hide();
                    $('#id_encryptionb_key').parent().hide();
                    $('#id_encryption_direction').parent().show();
                } else if(selectedMethod === 'affine') {
                    $('#id_encryption_key').parent().show();
                    $('#id_encryptionb_key').parent().show();
                    $('#id_encryption_direction').parent().hide();
                } else if(selectedMethod === '') {
                    $('#id_encryption_key').parent().hide();
                    $('#id_encryptionb_key').parent().hide();
                    $('#id_encryption_direction').parent().hide();
                }
            });
        });
    </script>
{% endblock %}
{% block content %}

    <h2>Compose Message</h2>
    {% if error_message %}
    <div class="error-message">
        {{ error_message }}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Send</button>
    </form>

{% endblock %}

app/templates/maxusers.html
<!DOCTYPE html>
<html>
<head>
    <title>Maximum Accounts Reached</title>
    <style>
        body {
        background-color: #222;
        color: #fff;
        font-family: Arial, sans-serif;
        text-align: center;
        padding: 50px;
        }
        h1 {
        font-size: 36px;
        }
        p {
        font-size: 18px;
        margin: 20px 0;
        }
        a {
        color: #3498db;
        text-decoration: none;
        }
        a:hover {
        text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>Maximum Accounts Reached</h1>
    <p>Sorry, but we have reached the maximum number of accounts that we can accept at this time. Please try again later or contact support if you have any questions.</p>
    <p><a href="{% url 'login' %}">Go back to the login page</a></p>
</body>
</html>